WITH PREP AS (
    SELECT
        PRODUCTION_DATE,
        TOYS_PRODUCED,
        LAG(TOYS_PRODUCED) OVER(ORDER BY PRODUCTION_DATE) AS PREVIOUS_DAY_PRODUCTION,
        TOYS_PRODUCED - LAG(TOYS_PRODUCED) OVER(ORDER BY PRODUCTION_DATE) PRODUCTION_CHANGE,
        (TOYS_PRODUCED - LAG(TOYS_PRODUCED) OVER(ORDER BY PRODUCTION_DATE))::FLOAT/LAG(TOYS_PRODUCED) OVER(ORDER BY PRODUCTION_DATE)*100.0 PRODUCTION_CHANGE_PERCENTAGE
    FROM
        TOY_PRODUCTION
)
SELECT
    PRODUCTION_DATE,
    TOYS_PRODUCED,
    PREVIOUS_DAY_PRODUCTION,
    PRODUCTION_CHANGE,
    PRODUCTION_CHANGE_PERCENTAGE
FROM
    PREP
WHERE
    PRODUCTION_CHANGE_PERCENTAGE IS NOT NULL
ORDER BY
    5 DESC LIMIT 1