SELECT
    C.NAME,
    C.CHILD_ID,
    G.NAME,
    PRICE
FROM
    GIFTS    G
    JOIN CHILDREN C
    ON G.CHILD_ID=C.CHILD_ID
WHERE
    PRICE > (SELECT AVG(PRICE) AS A_PRICE FROM GIFTS    )
ORDER BY
    PRICE ASC